"""baseline batch finding(raw) sheet_columns

Revision ID: e9f0efaf551e
Revises: 
Create Date: 2026-09-29 13:05:13.814290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9f0efaf551e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batch_is_latest'), ['is_latest'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sheet_key', sa.String(length=100), nullable=True),
    sa.Column('plugin_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('severity_raw', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('remediation_due', sa.Date(), nullable=True),
    sa.Column('first_extension_due', sa.Date(), nullable=True),
    sa.Column('exception_due', sa.Date(), nullable=True),
    sa.Column('effective_due', sa.Date(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=True),
    sa.Column('close_status', sa.String(length=30), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_close_status'), ['close_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_effective_due'), ['effective_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_sheet_key'), ['sheet_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_stage'), ['stage'], unique=False)

    op.create_table('sheet_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sheet_key', sa.String(length=100), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sheet_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheet_columns_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheet_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheet_columns_batch_id'))

    op.drop_table('sheet_columns')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_stage'))
        batch_op.drop_index(batch_op.f('ix_finding_sheet_key'))
        batch_op.drop_index(batch_op.f('ix_finding_severity'))
        batch_op.drop_index(batch_op.f('ix_finding_owner'))
        batch_op.drop_index(batch_op.f('ix_finding_host'))
        batch_op.drop_index(batch_op.f('ix_finding_effective_due'))
        batch_op.drop_index(batch_op.f('ix_finding_department'))
        batch_op.drop_index(batch_op.f('ix_finding_close_status'))
        batch_op.drop_index(batch_op.f('ix_finding_batch_id'))

    op.drop_table('finding')
    with op.batch_alter_table('import_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batch_is_latest'))

    op.drop_table('import_batch')
    # ### end Alembic commands ###
